books/urls.py
from django.urls import path

from .views import (
    book_list,
    book_detail,
    chapter_detail,
    exercise_detail,
)


app_name = "books"

urlpatterns = [
    path('', book_list, name="book_list"),
    path('<slug>/', book_detail, name="book_detail"),
    path('<book_slug>/<int:chapter_number>',
         chapter_detail, name="chapter_detail"),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>/',
         exercise_detail, name="exercise_detail"),
]

digital_market_project/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.shortcuts import redirect, reverse


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    publication_date = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:book_detail', kwargs={
            'slug': self.slug,
        })


class Chapter(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:chapter_detail', kwargs={
            'book_slug': self.book.slug,
            'chapter_number': self.chapter_number,
        })


class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('books:exercise_detail', kwargs={
            'book_slug': self.chapter.book.slug,
            'chapter_number': self.chapter.chapter_number,
            'exercise_number': self.exercise_number,
        })


class Solution(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    solution_number = models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return f"{self.exercise}-{self.pk}"

books/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from .models import Book, Chapter, Exercise


def book_list(request):
    # Display a list of the books
    queryset = Book.objects.all()
    context = {
        'queryset': queryset
    }
    return render(request, "book_list.html", context)


def book_detail(request, slug):
    # Display the book title and its chapters
    book = get_object_or_404(Book, slug=slug)
    context = {
        'book': book,
    }
    return render(request, "book_detail.html", context)


def chapter_detail(request, book_slug, chapter_number):
    chapter_qs = Chapter.objects \
        .filter(book__slug=book_slug) \
        .filter(chapter_number=chapter_number)
    if chapter_qs.exists():
        context = {
            "chapter": chapter_qs[0]
        }
        return render(request, "chapter_detail.html", context)
    return Http404


def exercise_detail(request, book_slug, chapter_number, exercise_number):
    exercise_qs = Exercise.objects \
        .filter(chapter__book__slug=book_slug) \
        .filter(chapter__chapter_number=chapter_number) \
        .filter(exercise_number=exercise_number)
    if exercise_qs.exists():
        context = {
            "exercise": exercise_qs[0]
        }
        return render(request, "exercise_detail.html", context)
    return Http404

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Digital Marketplace</title>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </ol>
        </nav>
        {% block content %}
        {% endblock content %}
    </div>

    <!-- JS Scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

templates/book_detail.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book_list' %}">Book List</a>
</li>
<li class="breadcrumb-item active" aria-current="page">
    {{ book.title }}
</li>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <main class="col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                {{ book.title }}
            </div>
            <img src="{{ book.cover.url }}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{ book.title }}</h5>
                <p class="card-text">
                    Published: {{ book.publication_date }}
                </p>
            </div>
        </div>
    </main>
    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Chapters
            </div>
            <ul class="list-group list-group-flush">
                {% for chapter in book.chapter_set.all %}
                <li class="list-group-item">
                    <a href="{{ chapter.get_absolute_url }}">
                        {{ chapter.chapter_number }}. {{ chapter.title }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </aside>
</div>
{% endblock content %}

templates/book_list.html
{% extends 'base.html' %}


{% block breadcrumb %}
<li class="breadcrumb-item active" aria-current="page">Book List</li>
{% endblock breadcrumb %}

<div class="row">

</div>

{% block content %}
<h1>Books</h1>
<hr>
<div class="row">
    {% for book in queryset %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">{{ book.title }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ book.publication_date }}</h6>
            <p class="card-text">
                {% for author in book.authors.all %}
                <span>{{ author }}</span>
                {% if book.authors.count > 1 %} | {% endif %}
                {% endfor %}
            </p>
            <a href="{{ book.get_absolute_url }}" class="card-link">{{ book }}</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

templates/chapter_detail.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book_list' %}">Book List</a>
</li>
<li class="breadcrumb-item" aria-current="page">
    <a href="{{ chapter.book.get_absolute_url }}">{{ chapter.book.title }}</a>
</li>
<li class="breadcrumb-item active" aria-current="page">
    {{ chapter }}
</li>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <main class="col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                {{ chapter.book.title }}
            </div>
            <img src="{{ chapter.book.cover.url }}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{ chapter.book.title }}</h5>
                <p class="card-text">
                    Published: {{ chapter.book.publication_date }}
                </p>
            </div>
        </div>
    </main>
    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Exercises
            </div>
            <ul class="list-group list-group-flush">
                {% for exercise in chapter.exercise_set.all %}
                <li class="list-group-item">
                    <a href="{{ exercise.get_absolute_url }}">
                        {{ exercise.exercise_number }}. {{ exercise.title }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </aside>
</div>
{% endblock content %}

templates/exercise_detail.html
{% extends 'base.html' %}

{% block breadcrumb %}
<li class="breadcrumb-item" aria-current="page">
    <a href="{% url 'books:book_list' %}">Book List</a>
</li>
<li class="breadcrumb-item" aria-current="page">
    <a href="{{ exercise.chapter.book.get_absolute_url }}">
        {{ exercise.chapter.book.title }}
    </a>
</li>
<li class="breadcrumb-item" aria-current="page">
    <a href="{{ exercise.chapter.get_absolute_url }}">
        {{ exercise.chapter.title }}
    </a>
</li>
<li class="breadcrumb-item active" aria-current="page">
    {{ exercise.title }}
</li>
{% endblock breadcrumb %}

{% block content %}
<div class="row">
    <main class="col-md-4">
        <div class="card" style="width: 18rem;">
            <div class="card-header">
                {{ exercise.chapter.book.title }}
            </div>
            <img src="{{ exercise.chapter.book.cover.url }}" class="card-img-top">
            <div class="card-body">
                <h5 class="card-title">{{ exercise.chapter.book.title }}</h5>
                <p class="card-text">
                    Published: {{ exercise.chapter.book.publication_date }}
                </p>
            </div>
        </div>
    </main>
    <aside class="col-md-8">
        <div class="card">
            <div class="card-header">
                Solutions
            </div>
            {% for solution in exercise.solution_set.all %}
            <div class="accordion" id="toggle-{{ solution.solution_number }}">
                <div class="card">
                    <div class="card-header" id="heading-{{ solution.solution_number }}">
                        <h2 class="mb-0">
                            <button class="btn btn-link" type="button" data-toggle="collapse"
                                data-target="#collapse-{{ solution.solution_number }}" aria-expanded="true"
                                aria-controls="collapse-{{ solution.solution_number }}">
                                Solution {{ solution.solution_number }}
                            </button>
                        </h2>
                    </div>

                    <div id="collapse-{{ solution.solution_number }}" class="collapse"
                        aria-labelledby="heading-{{ solution.solution_number }}"
                        data-parent="#toggle-{{ solution.solution_number }}">
                        <div class="card-body">
                            <img src="{{ solution.image.url }}" alt="" style="width: 100%;">
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </aside>
</div>
{% endblock content %}